export type CliFlags = Readonly<{
  help: boolean;
  setup: boolean;
  noCommit: boolean;
  regenerate: boolean;
  style: boolean;
  /** One-shot endpoint override (kebab flag --base-url -> camel key). */
  baseUrl?: string;
  instructions?: string;
  template?: string;
  provider?: string;
  model?: string;
}>;

export type ParseResult =
  | Readonly<{ ok: true; flags: CliFlags }>
  | Readonly<{ ok: false; error: string }>;

export const USAGE = `commitshi — commit messages from your staged changes, generated by a model

USAGE:
    commitshi [flags]

FLAGS:
    --setup                 Run the setup wizard: write baseurl/model/openai_api_key to ~/.config/commitshi/config, then exit
    --no-commit             Print the commit draft and stop; never commit
    --base-url <url>        One-shot endpoint override (default https://api.openai.com/v1)
    --regenerate            Generate a fresh commit draft for the same staged diff
    --instructions "<text>" One-shot instructions for the model (outranks the template)
    --style                 Add the last ~8 commit subjects to the prompt (opt-in; history is never read otherwise)
    --template "<string>"   One-shot template override (tokens: {type} {scope} {summary} {body})
    --provider <name>       One-shot provider override
    --model <name>          One-shot model override
    -h, --help              Show this help

Runs inside a git repository and reads only the staged changes.
`;

const VALUE_FLAGS: Readonly<Record<string, keyof CliFlags>> = {
  "--base-url": "baseUrl",
  "--instructions": "instructions",
  "--template": "template",
  "--provider": "provider",
  "--model": "model",
};

const BOOLEAN_FLAGS: Readonly<Record<string, keyof CliFlags>> = {
  "--no-commit": "noCommit",
  "--regenerate": "regenerate",
  "--style": "style",
  "--setup": "setup",
  "--help": "help",
  "-h": "help",
};

export function parseArgs(args: readonly string[]): ParseResult {
  const flags: Record<keyof Pick<CliFlags, "help" | "setup" | "noCommit" | "regenerate" | "style">, boolean> &
    Partial<Record<"baseUrl" | "instructions" | "template" | "provider" | "model", string>> = {
    help: false,
    setup: false,
    noCommit: false,
    regenerate: false,
    style: false,
  };

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];

    const valueName = VALUE_FLAGS[arg];
    if (valueName !== undefined) {
      const value = args[i + 1];
      if (value === undefined || value.startsWith("-")) {
        return { ok: false, error: `flag ${arg} requires a value` };
      }
      flags[valueName as "baseUrl"] = value;
      i++;
      continue;
    }

    const boolName = BOOLEAN_FLAGS[arg];
    if (boolName !== undefined) {
      (flags as Record<string, boolean>)[boolName] = true;
      continue;
    }

    return { ok: false, error: `unknown flag: ${arg}` };
  }

  return { ok: true, flags: flags as CliFlags };
}
